language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
    - 1.31.0
os:
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt || true) &&
      (travis_wait rustup component add clippy || true)

script:
    - ./ci-check.sh
